config/routes.rb
MyBookshop2::Application.routes.draw do
  

 

 
  post 'products/search', to: 'products#search'
  resources :products

 end

app/models/product.rb
# app\models\product.rb
class Product < ActiveRecord::Base

	validates :title, :presence => { :message => "cannot be blank ..."}
	validates :title, :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
	
	validates :description, :length => {:maximum => 200, :message => "maximum length 2000 characters"} 
  
	validates :img_url, :allow_blank => true, :format=> {:with => %r{\.(gif|jpg|png)$}i,:multiline => true, :message => "must be a URL for GIF, JPG or PNG images."}
	
	validates :price, :numericality => {:greater_than_or_equal_to => 0, :allow_blank => true, :message => "must be a positive value"}

	# see Timeliness GEM
	# validates :date_published, :timeliness => {  :type => :date,
	#		  :allow_blank => true, :invalid_date_message => "Date Published: is not a valid date ..."}

	# convert date to display in UK format
	def date_published_format
		if self.date_published !=nil
		#	self.date_published = date_published.strftime("%d-%m-%Y") 
		end
	end

	# a simple search which returns all objects whose title 
	# is the same as the value of a search_string
	def self.simple_search(search_string)
		self.where("title = ?", search_string)
	end

	# a fuzzy search which returns all objects whose title 
	# contains some part of the value of a search_string
	def self.fuzzy_search(search_string)
		title = "%" + search_string + "%"
		price = search_string
		self.where("title LIKE ? or price=?", title, price)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

end

app/controllers/products_controller.rb
# app\controllers\products_controller.rb
class ProductsController < ApplicationController
  
  # When this controller is called, this method is always run first.

  # The method 'set_product' found below, will be called for 'only' those 
  # actions indicated. Used to retrieve object data from the database.
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # This action uses the class method 'all' sent to the classs Product to get all products
  # similar to "SELECT * FROM PRODUCTS" , "@products" represents a collection of different 
  # product objects. Notice it is plural. Ordered by product title.
  def index
    @products = Product.all
  end

  # GET /products/1
  # The 'before_action' method above causes the private set_product' method to be called.
  # The class method 'find' is sent to the Product class to find an existing product by 
  # its id. The retrieved database record is used to create an instance variable @product .
  # The associated view 'show.html.erb' is called - using the instance variable @product . 
  def show
  end

  # GET /products/new
  # A new empty Product object '@product' is created, all attributes are blank.
  # This empty instance variable is sent to the view 'new.html.erb', @product is 
  # used in the blank form when entering new values.
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  # The 'before_action' method above causes the private set_product' method to be called.
  # The class method 'find' is sent to the Product class to find an existing product by 
  # its id. The retrieved database record is used to create an instance variable @product .
  # The associated view 'edit.html.erb' is called - using the instance variable @product, 
  # @product is used in the blank form when editing existing values.
  def edit
  end

# POST /products
# product_params is a hash object with all attribute values populated from a form used 
# in 'new' above. The attributes in product_params are used in a new method to create 
# a new product object. If the object's values are saved to the database then a flash 
# notice is displayed, else the 'new' action is called again so a user can alter any errors.
def create
@product = Product.new(product_params)
respond_to do |format|
if @product.save
format.html { redirect_to @product, notice: 'Product was successfully created.' }
format.json { render action: 'show', status: :created, location: @product }
else
format.html { render action: 'new' }
format.json { render json: @product.errors, status: :unprocessable_entity }
end
end
end

  # PATCH/PUT /products/1
  # this update action is run after a form is used to edit a record.
  # The 'before_action' method above causes the private 'set_product' method to be called
  # which instantiates a @product object from the database. This object is then updated with 
  # a call to product_params. The private method 'product_params'checks that the attributes 
  # used from the form are permitted.
  # If successful this action redirects the user to show.html.erb or it will again
  # render / display the edit form to correct any invalid data

  # When editing, the file_field img_url textbox holds the value of a product's newly 
  # browsed filename, while the textbox img_url displays any existing filename.
  # If a new filename has not been selected the file_field will remain empty but will
  # be used to update the product's record. 

  def update
    # temp_url_string is used to temporarily save from the database, an existing product's 
    # img_url filename.
    # temp_url_string = 
    if @product.update(product_params)
      # if product's img_url attribute from the form is blank
      
        # then a copy of the filename string is assigned to the img_url attribute 
        # @product.update_attribute
      # end
      # redirect_to @product, notice: 'Product was successfully updated.' 
      else
        render action: 'edit' 
      end
  end

  # DELETE /products/1
  # The 'before_action' method above causes the private set_product' method to be called.
  # The class method 'find' is sent to the Product class to find an existing product by 
  # its id. The retrieved database record is used to create an instance variable @product .
  # This object is then sent the message 'destroy' to delete the record from the database.
  # A redirection method, redirects to the products_path (products_url) which means ... products#index
  def destroy
    @product.destroy
    
  end

  # 'fuzzy_search' assigns to an instance variable collection '@products' all objects which include some 
  # of the search_string in their title, the collection is ordered by title.
  # If there are some products to display, this action redirects the user to the 'index' action.
  def search
    # @products = Product.simple_search(params[:search_string])
    @products = Product.fuzzy_search(params[:search_string])
    if @products.empty?
      flash.now[:alert] = "No records found - displaying all records ..."
      @products = Product.all.order :title
    end
    @products.order :title
    render :action => "index"
  end

  private
    # The 'before_action' method above causes the private 'set_product' method to be called.
    #
    #
    #
    def set_product
      @product = Product.find(params[:id])
    end

    # This private method is called by the actions; create and update. 
    # 'product_params' checks that only permitted attributes are allowed.
    # A hash 'params' of these parameter attributes and associated values is returned.
    def product_params
      params.require(:product).permit(:title, :description, :img_url, :price, :date_published)
      # returns 'params' a hash collection of keys and associated values.
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!-- app\views\layouts\application.html.erb -->
<!DOCTYPE html>
<html>
	<head>
	  <title>MyBookshop5</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="main-div">
			<div id="layout-top">
				<div id="title-top">
					<span>Books</span>
				</div>
				<div id="search-new-product">		
					<div id="book-search">
						<!-- add code to display a search box in this view, a 'partial' called _search.html.erb and a model method called 'search' -->
						<%= render(:partial=>'/search',:locals=>
               						{ :my_path => "/products/search" })%>
					</div> 
					<div id="new-product">
						<%= button_to 'New Product',new_product_path, 
							:method => :get,:title=>"select to add new product details ..."%>
					</div>
				</div>
				<!-- display error messages at the bottom of the header of every page 
		
				flash is a session variable, you can store error messages on one page
				and access them on another, it is a special 'hash' of symbols, it is cleared 
				after every request so it is only available for the next call
				-->
				<div id="feedback-top" style = "text-align: left"> 
					
					<!-- to display all params[] remove "#" to <%= logger.debug("") %> -->
					<%#= logger.debug("-----------------") %> 
					<%#= logger.debug params.to_s %> 
					<%#= logger.debug("-----------------") %> 
					
					<!-- display in red -->
					<% if flash[:alert] %>
						<div id="alert" ><%= flash[:alert] %></div>
					<% end %>
					<!-- display in green -->
					<% if flash[:notice] %>
						<div id="notice"><%= flash[:notice] %></div>
					<% end %>		
				</div>
			</div>
			<!-- include selected page -->
			<%= yield %>
		</div>
	</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description, "Description:" %><br>
    <%= f.text_area :description, :cols => 32 %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url, :size => 42 %> <br>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, :size => 25 %>
  </div>

  <div class="field">
    <%= f.label :date_published %><br>
    <%#= f.date_select :date_published %>
    <div class="datepicker"> 
      <% @product.date_published_format %> 
      <%= f.text_field :date_published %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/edit.html.erb
<!-- app\views\edit.html.erb -->
<%= render "/error_messages", :message_header => "Cannot save: ", :target => @product %> 

<div class="form1">
	<div class="main-title">Edit a Product</div>
		<%= render 'form' %>

		<%= link_to 'Show', @product %> |
		<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<!– app\views\products\index.html.erb -->
<div id="all-content"> 
  <% @products.each do |product| %>
    <div id="product-box">
      <fieldset> 

        <div id="img-box" , title="select image for more details ..." >
          <% if not product.img_url.blank? %>
            <%= link_to (image_tag product.img_url,:size => "100x125"),product %>
          <% else %>
            <%= link_to (image_tag("no-image.jpg",:size => "100x125")),product %>
          <% end %>
        </div>

        <div id="details-box">
          <div id="title-box">
            <%= product.title %>
          </div>
          <div id="published-box">
            <% if not product.date_published.blank? %>
             Published: <%= product.date_published.strftime("%Y") %>
            <% end %> 
          </div>
          <div id="admin-box">
           <%#= link_to 'Show', product %>
           <%= link_to 'Edit', edit_product_path(product) %>
           <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>    
      </fieldset> 
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<!-- app\views\new.html.erb -->
<%= render "/error_messages", :message_header => "Cannot save: ", :target => @product %> 

<div class="form1">
	<div class="main-title">New Product</div>
	<%= render 'form' %>
	<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div id="show-img">    
  
<div class="main-title"> <%= @product.title %> </div> 

<!-- display an image using a product's img_url or if blank 
      display an image reading "no image to display" -->
<%= image_tag  @product.img_url, size: "200x250" %> 
<br/><br/>  

<!-- if a product does not have a price then do not display -->
<div class="sub-title"> 
Price: <%= @product.price %>    
</div>
  
<div class="sub-title">
Date published:<%= @product.date_published %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |


<%= @product.description %>  
</div>

		
		
		